# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e6b7313c6f7a5d3a7e67dde898fc8705e98c290197579dcab0aa0ffd6d8328848e76919031969e24d042e114a7c27a75ec9499cbcd37596d06ed86f095d8c65
  omniauth: &omniauth_dev
    facebook:
      app_id: '693705734041882'
      app_secret: 'd6c47cfe73359294ad9c40d890223b91'
    vkontakte:
      app_id: '3981216'
      app_secret: 'IgpVQNiWML6ksioGQYOH'
    github:
      app_id: 'e63f0756375e4eaf35b3'
      app_secret: '76f6e298373603ba57d48fa54c90ebfd5af43340'
test:
  secret_key_base: 76b60e712b67da0ecc8ce62739c9ba607d8e09f976f9f327ee210707a77c93161efdfc018be52b622127f2c464dffc35f5312f12ab4513e2807d5bcb50f6e26d
  omniauth:
    <<: *omniauth_dev

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth:
    facebook:
      app_id: <%= ENV["FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
    vkontakte:
      app_id: <%= ENV["VKONTAKTE_APP_ID"] %>
      app_secret: <%= ENV["VKONTAKTE_APP_SECRET"] %>
    github:
      app_id: <%= ENV["GITHUB_APP_ID"] %>
      app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
